name: blue_ride
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cloud_firestore: ^4.0.5
  country_icons: ^2.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  fl_country_code_picker: ^0.0.4
  flutter:
    sdk: flutter
  flutter_google_places: ^0.3.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  google_maps_webservice: ^0.0.19
  http: ^0.13.5
  pinput: ^2.2.16
  provider: ^6.0.4
  uuid: ^3.0.7
  animated_text_kit: ^4.2.2
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
