// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHwdSTt-k-DmnRdW8zAg7I2516QKlduXM',
    appId: '1:949346493558:android:76a337f019ad9bef836b57',
    messagingSenderId: '949346493558',
    projectId: 'pleas-work',
    storageBucket: 'pleas-work.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChLafBicVOvUmKlxJG_Wfg1z82cAV234Y',
    appId: '1:949346493558:ios:5a3982946516d1a4836b57',
    messagingSenderId: '949346493558',
    projectId: 'pleas-work',
    storageBucket: 'pleas-work.appspot.com',
    androidClientId: '949346493558-ie329sblki9qacjfirle0f9cbhtb52of.apps.googleusercontent.com',
    iosClientId: '949346493558-phdn1hsc8ajdvfslpojsqdjkui1msp6r.apps.googleusercontent.com',
    iosBundleId: 'com.onatcipli.networkUpp',
  );
}
